### ISSUE TITLE
Gulpfile is missing

### ISSUE THREAD

**Issue by pbastowski** [asoldino/ng2-starter#1]
I was trying to use ng2-starter this evening, and so I did this

``` bash
$ npm i -D ng2-starter
```

Which installed a lot of stuff in `node_modules`. 

Then I did this

``` bash
$ la
total 8
drwxr-xr-x    4 paul  staff    136 Jan 26 22:21 ./
drwxr-xr-x    5 paul  staff    170 Jan 26 22:20 ../
drwxr-xr-x  345 paul  staff  11730 Jan 26 22:21 node_modules/
-rw-r--r--    1 paul  staff    285 Jan 26 22:21 package.json
```

Only two files listed here. Is there supposed to be a `gulpfile.js` here also?

So, I thought perhaps there are some scripts like `CI` and `clean` in `package.json`'s scripts section, but alas, they are not there - see below.

``` bash
$ cat package.json 
{
  "name": "ng2-starter-npm",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": 
    "ng2-starter": "^1.0.8"
  }
}
```

Am I missing some step?

**Comment by asoldino** [comment]
Yes you need to require my lib and call it as a function passing your confit object if you want. I forgot to push the latest read me sorry 

Inviato da iPhone

**Comment by asoldino** [comment]
I updated the readme on github

J

**Comment by pbastowski** [comment]
Thanks, that worked.

I think the items below could be added to the readme to make things easier for the user:
- a sample `tsconfig.json`
- the minimum `gulpfile.js` file

And a suggestion on how to install the compiler and angular2
- `npm i -D typescript@next`
- `npm i -D angular2@2.0.0-beta.0`

Perhaps the sample TS config file could even be placed int he src folder, ready to be modified (or not). Same for the gulpfile.

**Comment by asoldino** [comment]
Hey Paul,

thanks for the suggestions. I implemented them inside the README.md. About the possibility of bringing along some precompiled tsconfig.json and/or gulpfile.js I prefer not because I don't personally like these copy from here to there kind of procedures. IMHO it is always better to spend five minutes to figure out what you are trying to accomplish and how, because each project will be different. A sample is ready inside the README tho, as you suggested.

**Comment by pbastowski** [comment]
Thanks.
